### PR TITLE
chore: Changes to analytics names and timing

### PR DESCRIPTION
**Pull request by rainandbare**
<details open>
  <summary>Argus Stack Details</summary>
  <br />
  <table>
    <tr>
      <th>Name</th>
      <td>rainandbare-7299-analytics-turn-on-only</td>
    </tr>
    <tr>
      <th>Short Name</th>
      <td>just-lamb</td>
    </tr>
    <tr>
      <th>Base URL</th>
      <td><a href="https://just-lamb.dev-sc.dev.czi.team" target="_blank">https://just-lamb.dev-sc.dev.czi.team</a></td>
    </tr>
  </table>
</details>

---

Addresses issue [#7299](https://github.com/chanzuckerberg/single-cell-data-portal/issues/7299)

Renames:

- EXPLORER_CLIP to EXPLORER_CLIP_SELECTED
- EXPLORER_VISUALIZATION_SETTINGS_BUTTON_CLICKED to EXPLORER_CLIP_CLICKED

Only Trigger when feature is toggled on:

- EXPLORER_SHOW_LABELS
- EXPLORER_CLIP_CLICKED
- EXPLORER_GENE_VIEW_DISTRIBUTION
- EXPLORER_COLORBY_GENE
- EXPLORER_COLORBY_GENE_SET

Checklist before Merge

- [x]  Once event updates are deployed to Staging ping @ainfeld to check analytics
- [x]  Verify events are showing up in the Staging space in Plausible correctly

### CODE REVIEW

**Comment by tihuan** [comment]
Wow so fast 🔥 You're amazing, @rainandbare !!

I added `stack` label to get an rdev 👍 !

**Comment by tihuan** [comment]
@rainandbare we might need to uncomment `// console.log("track", event, options);` temporarily for @ainfeld to verify the events in rdev 🙏 

Thank you!

**Review by tihuan — APPROVED** [review]
Code LGTM 👏 ! Just need @ainfeld to verify the events in rdev now 🙏 

Thanks all 🚀 !!

**Comment by ainfeld** [comment]
thanks!! @rainandbare what url should I look at to test out the events?

**Comment by ainfeld** [comment]
Thanks!! @rainandbare I tried clicking the base URL above but it's not working. What URL should I look at to test out the events?

**Comment by rainandbare** [comment]
> Thanks!! @rainandbare I tried clicking the base URL above but it's not working. What URL should I look at to test out the events?

Yeah - I see that too! Let me see what I can do. ⏳

**Pull request merged**
