### PR TITLE
feat: 88 add dataset_id to the metadata endpoint

### PR DESCRIPTION
**Pull request by ebezzi**
#### Reviewers
**Functional:** 
@seve @MillenniumFalconMechanic 

---

## Changes
- Adds the `dataset_id` to the metadata endpoint

### CODE REVIEW

**Review by MillenniumFalconMechanic — APPROVED** [review]
LGTM, thank you @ebezzi!

**Review by MDunitz — APPROVED** [review]
Just checking what are we using the dataset id for? if it is to link to the explorer we should use the explorer_url instead bc there are datasets that dont use the id in the url

**Comment by ebezzi** [comment]
> Just checking what are we using the dataset id for? if it is to link to the explorer we should use the explorer_url instead bc there are datasets that dont use the id in the url

@MillenniumFalconMechanic do you know? Madison has a good point.

**Comment by MillenniumFalconMechanic** [comment]
We need a mechanism to filter out the current dataset from `collection_datasets` array so we can display only the sibling datasets in the dropdown menu.

**Pull request merged**
