### PR TITLE
chore: upgrade argus helm stack chart

### PR DESCRIPTION
**Pull request by jakeyheath**
<details open>
  <summary>Argus Stack Details</summary>
  <br />
  <table>
    <tr>
      <th>Name</th>
      <td>jakeyheath-patch-1</td>
    </tr>
    <tr>
      <th>Short Name</th>
      <td>correct-haddock</td>
    </tr>
    <tr>
      <th>Base URL</th>
      <td><a href="https://correct-haddock.dev-sc.dev.czi.team" target="_blank">https://correct-haddock.dev-sc.dev.czi.team</a></td>
    </tr>
  </table>
</details>

---

https://czi.atlassian.net/browse/CCIE-3465

Prep for upgrading clusters to support custom domains

### CODE REVIEW

**Comment by jakeyheath** [comment]
verified my stack didn't break anything

**Review by hspitzley-czi — COMMENTED** [review]
LGTM but lets wait for approval from team

**Comment by jakeyheath** [comment]
@tihuan @ebezzi mind taking a look at this PR when you get a chance?

**Review by tihuan — APPROVED** [review]
LGTM!! Thank you 😁

**Pull request merged**
