### PR TITLE
Remove auth code [zh1278]

### PR DESCRIPTION
**Pull request by blrnw3**
## Changes
Remove all auth/user code from server and client

https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1278

## Verification
Tested with a local run

### CODE REVIEW

**Comment by blrnw3** [comment]
Let me know if we need to add a frontend specialist to review the client code

**Review by MDunitz — APPROVED** [review]
lgtm -- but it might be worth having @seve or @tihuan take a look at the front end code. 
Can you create a pr in single-cell-infra updating the config files for all envs to remove the auth config params?

Also it looks like there is an issue with the smoke tests?

**Comment by blrnw3** [comment]
Thanks Madison. Fixed the smoke tests - had forgot to clean up the client tests 😬 
infra pr is here https://github.com/chanzuckerberg/single-cell-infra/pull/424

**Comment by blrnw3** [comment]
Checked with Seve's corresponding desktop pr and looks like i got everything, will merge

**Review by tihuan — APPROVED** [review]
FE code LGTM!! Thanks so much for removing this, Ben 🙏 !!

**Pull request merged**
