### PR TITLE
chore: updating logo

### PR DESCRIPTION
**Pull request by ashin-czi**
#385 

#### Reviewers
**Functional:** @seve @ambrosejcarr 

**Readability:** @seve @ambrosejcarr 

---

## Changes
- add
- remove
- modify
    - Favicon

### CODE REVIEW

**Comment by ashin-czi** [comment]
So since the top left logo icon is just an SVG element of styled rectangles, I just changed the colors to match the rebranding:

image

**Comment by ashin-czi** [comment]
Cleaned up the new logo, let me know your thoughts:
image

**Review by seve — APPROVED** [review]

**Comment by ambrosejcarr** [comment]
@hthomas-czi can you provide guidance on the right logo to use here?

**Comment by ashin-czi** [comment]
@ambrosejcarr @hthomas-czi Just wanted to see if I could get an update for what direction we should take for this

Currently the Explorer logo icon is just an HTML SVG element of rectangles, styled to resemble the logo. So it doesn't use any image for the logo currently.

I made updates to have the new icon match the rebranded logo as close that I can, but need a decision to whether keep using the HTML elements, or use the PNG image for the logo.

**Comment by hthomas-czi** [comment]
@ashin-czi This logo doesn't need to be updated. It will be removed as part of [#382](https://github.com/chanzuckerberg/single-cell-explorer/pull/382).

**Comment by ashin-czi** [comment]
> @ashin-czi This logo doesn't need to be updated. It will be removed as part of [#382](https://github.com/chanzuckerberg/single-cell-explorer/pull/382).

Good to know, thank you! Do you know if this is also the case for CellxGene Annotate? I believe that also has the top left icon on the visualize UI.

**Review by seve — APPROVED** [review]

**Comment by ashin-czi** [comment]
Ready for staging

**Pull request merged**
