### PR TITLE
Dunitz/1280 remove annotations code

### PR DESCRIPTION
**Pull request by MDunitz**
#### Reviewers
**Functional:** 
- @atolopko-czi 
**Readability:** 

---

## Changes
- remove code for annotations feature/db testing to unblock staging deployment

### CODE REVIEW

**Comment by atolopko-czi** [comment]
Locally running `make unit_test` for `backend/czi_hosted`, I did get failure: `ERROR: test_run (backend.test.test_czi_hosted.unit.eb.test_eb.Elastic_Beanstalk_Test)`.

**Comment by atolopko-czi** [comment]
> Locally running `make unit_test` for `backend/czi_hosted`, I did get failure: `ERROR: test_run (backend.test.test_czi_hosted.unit.eb.test_eb.Elastic_Beanstalk_Test)`. Just need to rm ` $(MAKE) clean-test-db; \` in Makefile:18.

Actually, the EB test failure is unrelated to the errant `clean-test-db` target being run. Still need to remove that. 

Can the EB tests actually be run locally? I don't think it's doing any *real* AWS EB stuff, so probably should be working for me, right?

**Comment by MDunitz** [comment]
> > Locally running `make unit_test` for `backend/czi_hosted`, I did get failure: `ERROR: test_run (backend.test.test_czi_hosted.unit.eb.test_eb.Elastic_Beanstalk_Test)`. Just need to rm ` $(MAKE) clean-test-db; \` in Makefile:18.
> 
> Actually, the EB test failure is unrelated to the errant `clean-test-db` target being run. Still need to remove that.
> 
> Can the EB tests actually be run locally? I don't think it's doing any _real_ AWS EB stuff, so probably should be working for me, right?

The eb tests usually fail when I run them locally, but its still worth removing the clean-test-db command

**Review by atolopko-czi — APPROVED** [review]
Removals of test-db seem reasonable, so approving.  GH Action tests passed, so assuming that means staging deploy via single-cell-infra will also be successful

**Pull request merged**
