### PR TITLE
feat: add deployed_version endpoint

### PR DESCRIPTION
**Pull request by ebezzi**
#582 
Adds a `deployed_version` endpoint.

### CODE REVIEW

**Review by Bento007 — COMMENTED** [review]
Add a test for this endpoint

**Review by atolopko-czi — CHANGES_REQUESTED** [review]
LGTM but let's also add a simple test to `test_api_v3.py`, to keep code coverage from falling.

Also note that I added a follow-up task to the issue to update the deployment checklist.

**Comment by ebezzi** [comment]
I will add a test, but note that it won't guarantee the endpoint to work since it's environment/infra dependent.

**Review by atolopko-czi — APPROVED** [review]
👏

**Comment by metakuni** [comment]
Can this be merged?

**Review by Bento007 — APPROVED** [review]

**Pull request merged**
